### ISSUE TITLE
How to upload documents with custom fields?

### ISSUE THREAD

**Issue by Zackgar** [LuminosoInsight/luminoso-api-client-python#53]
I'm unable to upload my dataset via the UI so I was hoping I could use this API to do so.

My datasets relies on custom fields (mostly `string_`), how may I specify the in the document upload of the API? Just as a top-level attribute `string_VAR` in the document?

**Comment by jhaberluminoso** [comment]
Hi Zackgar,

We're happy to help. To get started, I'd like to troubleshoot why you are unable to upload your dataset via the UI. 

Are you seeing an error message? If so, could you please provide a screenshot so that we may troubleshoot further. 

In regards to the API. As you have correctly identified, you will want to specify in each document the string value. Below is a link to our API documentation around filters - string, date, and number fields.

https://analytics.luminoso.com/api/v5/#Filters

For most prompt assistance, please email support@luminoso.com.

Best,
Luminoso Customer Success Team

**Comment by Zackgar** [comment]
So I can upload a document such as 
```
{
'title': 'Foo',
'text': '...',
'string_Field_A': 'somevalue'
}
```

And I will be able to filter by `Field A` via the UI and API, correct?

Regarding the UI error, the browser seems to time out on the upload (¬100MB files)
